name: Update SOCKS5 Proxy List   

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch and update proxies
        run: |
          curl -s "https://raw.githubusercontent.com/VPSLabCloud/VPSLab-Free-Proxy-List/refs/heads/main/socks5_all.txt" > all.txt
          curl -s "https://github.com/proxygenerator1/ProxyGenerator/raw/refs/heads/main/Unstable/socks5.txt" >> all.txt
          curl -s "https://raw.githubusercontent.com/ClearProxy/checked-proxy-list/main/socks5/raw/all.txt" >> all.txt
          sort -u all.txt -o all.txt

      - name: Commit and push updated file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add all.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update SOCKS5 proxy list" && git push)
